//CASE Çalışması olduğu için tüm Dataları grafikte göstermedim.Örnek olarak hazırlanmıştır.

export const generateChartData = (data: any) => {
  return {
    labels: data?.map((item: any) =>
      new Date(item["Tarih"]).toLocaleDateString("tr-TR")
    ),
    datasets: [
      {
        label: "Oda",
        data: data?.map((item: any) => item["Oda"]),
        backgroundColor: "rgba(75, 192, 192, 0.2)",
        borderColor: "rgba(75, 192, 192, 1)",
        borderWidth: 1,
      },
      {
        label: "Yetişkin",
        data: data?.map((item: any) => item["Yetişkin"]),
        backgroundColor: "rgba(75, 50, 60, 0.2)",
        borderColor: "rgba(75, 192, 192, 1)",
        borderWidth: 1,
      },
      {
        label: "Çocuk",
        data: data?.map((item: any) => item["Çocuk"]),
        backgroundColor: "rgba(75, 100, 256, 0.2)",
        borderColor: "rgba(75, 192, 192, 1)",
        borderWidth: 1,
      },
      {
        label: "Free",
        data: data?.map((item: any) => item["Free"]),
        backgroundColor: "rgba(75, 100, 256, 0.2)",
        borderColor: "rgba(75, 192, 192, 1)",
        borderWidth: 1,
      },
      {
        label: "Toplam Kişi",
        data: data?.map((item: any) => item["Toplam Kişi"]),
        backgroundColor: "rgba(75, 210, 26, 0.2)",
        borderColor: "rgba(75, 192, 192, 1)",
        borderWidth: 1,
      },
      //.....Devam ettirilebilir yada tüm keyler bir array içerisine alınıp dinamik bir şekilde for ile dönülebilir. case study için sınırlı tutulmuştur
      // const getRandomColor = () => {
      //   const letters = '0123456789ABCDEF';
      //   let color = '#';
      //   for (let i = 0; i < 6; i++) {
      //     color += letters[Math.floor(Math.random() * 16)];
      //   }
      //   return color;
      // };

      // // Datasetler
      // const datasets = [
      //   { label: "Oda", key: "Oda" },
      //   { label: "Pax", key: "Pax" },
      //   { label: "Free", key: "Free" },
      //   { label: "Yetişkin", key: "Yetişkin" },
      //   { label: "Çocuk", key: "Çocuk" },
      //   { label: "Toplam Kişi", key: "Toplam Kişi" },
      //   { label: "Yüzde%", key: "Yüzde%" },
      //   { label: "Mevcut", key: "Mevcut" },
      //   { label: "Konum1", key: "Konum1" },
      //   { label: "Konum2", key: "Konum2" },
      //   { label: "Konum3", key: "Konum3" },
      //   { label: "Konum4", key: "Konum4" },
      //   { label: "Konum5", key: "Konum5" },
      //   { label: "Konum6", key: "Konum6" },
      //   { label: "Konum1%", key: "Konum1%" },
      //   { label: "Konum2%", key: "Konum2%" },
      //   { label: "Konum3%", key: "Konum3%" },
      //   { label: "Konum4%", key: "Konum4%" },
      //   { label: "Konum5%", key: "Konum5%" },
      //   { label: "Forecast", key: "Forecast" },
      //   { label: "Forecast Satılan", key: "Forecast Satılan" },
      //   { label: "Forecast Kalan", key: "Forecast Kalan" },
      //   { label: "Son Durum", key: "Son Durum" },
      //   { label: "Yüzde%(Sondurum)", key: "Yüzde%(Sondurum)" },
      //   { label: "Yüzde%(Net)", key: "Yüzde%(Net)" },
      //   { label: "Mevcut(Net)", key: "Mevcut(Net)" },
      //   { label: "Kalan_1", key: "Kalan_1" },
      //   { label: "Kalan_2", key: "Kalan_2" },
      //   { label: "Kalan_3", key: "Kalan_3" },
      //   { label: "Kalan_4", key: "Kalan_4" },
      //   { label: "Kalan_5", key: "Kalan_5" },
      //   { label: "Kalan_6", key: "Kalan_6" },
      //   { label: "Gelen Oda", key: "Gelen Oda" },
      //   { label: "Gelen Yetişkin", key: "Gelen Yetişkin" },
      //   { label: "Gelen Çocuk", key: "Gelen Çocuk" },
      //   { label: "Gelen Free", key: "Gelen Free" },
      //   { label: "Gelen Pax", key: "Gelen Pax" },
      //   { label: "Gelen Top Kişi", key: "Gelen Top Kişi" },
      //   { label: "Giden Oda", key: "Giden Oda" },
      //   { label: "Giden Yetişkin", key: "Giden Yetişkin" },
      //   { label: "Giden Çocuk", key: "Giden Çocuk" },
      //   { label: "Giden Free", key: "Giden Free" },
      //   { label: "Giden Pax", key: "Giden Pax" },
      //   { label: "Giden Toplam Kişi", key: "Giden Toplam Kişi" },
      //   { label: "Arızalı Oda", key: "Arızalı Oda" },
      //   { label: "Kapalı Oda", key: "Kapalı Oda" },
      //   { label: "Yatak(Mevcut)", key: "Yatak(Mevcut)" },
      //   { label: "Yatak%", key: "Yatak%" },
      //   { label: "Doviz Tutar", key: "Doviz Tutar" },
      //   { label: "Doviz Gerçek", key: "Doviz Gerçek" },
      //   { label: "TL Gerçek", key: "TL Gerçek" },
      //   { label: "Brut Tutar", key: "Brut Tutar" },
      //   { label: "Birleşme", key: "Birleşme" },
      //   { label: "Birleşme Trace", key: "Birleşme Trace" },
      //   { label: "Stop", key: "Stop" },
      //   { label: "Pm Sanal", key: "Pm Sanal" },
      //   { label: "Pax(P)", key: "Pax(P)" },
      //   { label: "Bebek", key: "Bebek" },
      //   { label: "Paxp Yetişkin", key: "Paxp Yetişkin" },
      //   { label: "Paxp Çocuk", key: "Paxp Çocuk" },
      //   { label: "Paxp Free", key: "Paxp Free" },
      //   { label: "Kontenjan Oda", key: "Kontenjan Oda" },
      //   { label: "Kontenjan Satılan", key: "Kontenjan Satılan" },
      //   { label: "Kontenjan Kalan", key: "Kontenjan Kalan" },
      //   { label: "Tentative Oda", key: "Tentative Oda" },
      //   { label: "Müşteri Tipi(1)", key: "Müşteri Tipi(1)" },
      //   { label: "Müşteri Tipi(2)", key: "Müşteri Tipi(2)" },
      //   { label: "Müşteri Tipi(3)", key: "Müşteri Tipi(3)" },
      //   { label: "Müşteri Tipi(4)", key: "Müşteri Tipi(4)" },
      //   { label: "Müşteri Tipi(5)", key: "Müşteri Tipi(5)" },
      //   { label: "Müşteri Tipi(6)", key: "Müşteri Tipi(6)" },
      //   { label: "Müşteri Tipi(7)", key: "Müşteri Tipi(7)" },
      //   { label: "Müşteri Tipi(8)", key: "Müşteri Tipi(8)" },
      //   { label: "Comp Oda", key: "Comp Oda" },
      //   { label: "Info Oda", key: "Info Oda" },
      //   { label: "House Use Oda", key: "House Use Oda" },
      //   { label: "Net Oda", key: "Net Oda" },
      //   { label: "NoShow", key: "NoShow" },
      //   { label: "Day Use", key: "Day Use" },
      //   { label: "Forecasttan Kalan(Tek)", key: "Forecasttan Kalan(Tek)" },
      //   { label: "Blokajsız Oda", key: "Blokajsız Oda" },
      //   { label: "Forecast Gelir", key: "Forecast Gelir" },
      //   { label: "Gun Tarih", key: "Gun Tarih" },
      //   { label: "Package Tutar", key: "Package Tutar" },
      //   { label: "Arızalı Toplam", key: "Arızalı Toplam" },
      //   { label: "Pax(Prm)", key: "Pax(Prm)" },
      //   { label: "Ort.Pax(Prm)", key: "Ort.Pax(Prm)" },
      //   { label: "Satılan-Birleşme", key: "Satılan-Birleşme" },
      //   { label: "Pax(Y/C2)", key: "Pax(Y/C2)" },
      //   { label: "His_For", key: "His_For" },
      //   { label: "Otel Kodu", key: "Otel Kodu" },
      //   { label: "Otel Adı", key: "Otel Adı" },
      //   { label: "Son_Yuzdem", key: "Son_Yuzdem" },
      //   { label: "Ort_Oda_Brut", key: "Ort_Oda_Brut" },
      //   { label: "Ort_Paxp_Brut", key: "Ort_Paxp_Brut" },
      //   { label: "Fark_Yuzde", key: "Fark_Yuzde" },
      //   { label: "Package Kdvsiz", key: "Package Kdvsiz" },
      //   { label: "Kdv%", key: "Kdv%" },
      //   { label: "Kon.Vergisi%", key: "Kon.Vergisi%" },
      //   { label: "Package Kdv", key: "Package Kdv" },
      //   { label: "Package Kon.Vergisi", key: "Package Kon.Vergisi" },
      //   { label: "TarihAy", key: "TarihAy" },
      // ];

      // return {
      //   labels: data?.map((item) => item["Tarih"]),
      //   datasets: datasets.map(dataset => ({
      //     label: dataset.label,
      //     data: data?.map((item) => item[dataset.key]),
      //     backgroundColor: getRandomColor(),
      //     borderColor: getRandomColor(),
      //     borderWidth: 1,
      //   })),
      // };
    ],
  };
};
