export const tableHeaders: string[] = [
  "Index",
  "Tarih",
  "Oda",
  "Pax",
  "Free",
  "Yetişkin",
  "Çocuk",
  "Toplam Kişi",
  "Yüzde%",
  "Mevcut",
  "Konum1",
  "Konum2",
  "Konum3",
  "Konum4",
  "Konum5",
  "Konum6",
  "Konum1%",
  "Konum2%",
  "Konum3%",
  "Konum4%",
  "Konum5%",
  "Forecast",
  "Forecast Satılan ",
  "Forecast Kalan",
  "Son Durum",
  "Yuzde%(Sondurum)",
  "Yuzde%(Net)",
  "Mevcut(Net)",
  "Kalan_1",
  "Kalan_2",
  "Kalan_3",
  "Kalan_4",
  "Kalan_5",
  "Kalan_6",
  "Gelen Oda",
  "Gelen Yetişkin",
  "Gelen Çocuk",
  "Gelen Free",
  "Gelen Pax",
  "Gelen Top Kişi",
  "Giden Oda",
  "Giden Yetişkin",
  "Giden Çocuk",
  "Giden Free",
  "Giden Pax",
  "Giden Toplam Kişi",
  "Arızalı Oda",
  "Kapalı Oda",
  "Yatak(Mevcut)",
  "Yatak%",
  "Doviz Tutar",
  "Doviz Gerçek",
  "TL Gerçek",
  "Brut Tutar",
  "Birleşme",
  "Birleşme Trace",
  "Stop",
  "Yatak%",
  "Pm Sanal",
  "Pax(P)",
  "Bebek",
  "Paxp Yetişkin",
  "Paxp Çocuk",
  "Paxp Free",
  "Kontenjan Oda",
  "Kontenjan Satılan ",
  "Kontenjan Kalan",
  "Tentative Oda",
  "Müşteri Tipi(1)",
  "Müşteri Tipi(2)",
  "Müşteri Tipi(3)",
  "Müşteri Tipi(4)",
  "Müşteri Tipi(5)",
  "Müşteri Tipi(6)",
  "Müşteri Tipi(7)",
  "Müşteri Tipi(8)",
  "Comp Oda",
  "Info Oda",
  "House Use Oda",
  "Net Oda",
  "NoShow",
  "Day Use",
  "Forecasttan Kalan(Tek)",
  "Blokajsız Oda",
  "Forecast Gelir",
  "Gun Tarih",
  "Package Tutar",
  "Arızalı Toplam",
  "Pax(Prm)",
  "Ort.Pax(Prm)",
  "Satılan-Birleşme",
  "Pax(Y/C2)",
  "His_For",
  "Otel Kodu",
  "Otel Adı",
  "Son_Yuzdem",
  "Ort_Oda_Brut",
  "Ort_Paxp_Brut",
  "Fark_Yuzde",
  "Package Kdvsiz",
  "Kdv%",
  "Kon.Vergisi%",
  "Package Kdv ",
  "Package Kon.Vergisi",
  "TarihAy",
];

export const blackListTableHeader = [
  "Id",
  "Adi",
  "Soy",
  "Aciklama",
  "Tcno",
  "Kimlik_no",
  "Dogum_tarihi",
  "Sistem_tarihi",
  "Sistem_grubu",
  "Otel_kodu",
  "Ulke_xml",
  "Kulanici",
  "Acenta",
  "Xml Kodu",
  "ULke Adı",
];

export const addNewRegister = [" db_Id", "Id", "Adi", "Soy", "Aciklama"];

export const navTitles = [
  "Satış ve Acenta İşlemleri",
  "Rezervasyon",
  "Resepsiyon",
  "Ön Kasa",
  "Kat Hizmetleri",
  "Santral",
  "Gece İşlemleri",
  "Raporlar",
  "Tanımlamalar",
];
